// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	modelsv1 "github.com/codingexplorations/data-lake/models/v1"
	mock "github.com/stretchr/testify/mock"
)

// SqsLogger is an autogenerated mock type for the SqsLogger type
type SqsLogger struct {
	mock.Mock
}

// sendLogMessage provides a mock function with given fields: msg, logLevel
func (_m *SqsLogger) sendLogMessage(msg string, logLevel modelsv1.Log_LogLevel) {
	_m.Called(msg, logLevel)
}

// NewSqsLogger creates a new instance of SqsLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSqsLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *SqsLogger {
	mock := &SqsLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
